export type OrderEventKind = "ORDER_CREATED" | "STATUS_TRANSITION" | "PAYMENT_REPORTED" | "PAYMENT_REJECTED" | "PAYMENT_AND_ORDER_CONFIRMED" | "PENDING_EXPIRED" | "NO_SHOW_RECORDED" | "REFUND_REQUIRED" | "REFUNDED";
export type WorkflowAction = "CONFIRM_PAYMENT_AND_ORDER" | "EXPIRE_PENDING" | "MARK_NO_SHOW" | "REPORT_PAYMENT" | "REJECT_PAYMENT" | "REQUIRE_REFUND" | "MARK_REFUNDED";

export function workflowActionEventKind(action: WorkflowAction): Exclude<OrderEventKind, "ORDER_CREATED" | "STATUS_TRANSITION"> {
  return action === "CONFIRM_PAYMENT_AND_ORDER" ? "PAYMENT_AND_ORDER_CONFIRMED" : action === "EXPIRE_PENDING" ? "PENDING_EXPIRED" : action === "MARK_NO_SHOW" ? "NO_SHOW_RECORDED" : action === "REPORT_PAYMENT" ? "PAYMENT_REPORTED" : action === "REJECT_PAYMENT" ? "PAYMENT_REJECTED" : action === "REQUIRE_REFUND" ? "REFUND_REQUIRED" : "REFUNDED";
}
