CREATE TYPE "OrderEventKind" AS ENUM ('ORDER_CREATED', 'STATUS_TRANSITION', 'PAYMENT_REPORTED', 'PAYMENT_REJECTED', 'PAYMENT_AND_ORDER_CONFIRMED', 'PENDING_EXPIRED', 'NO_SHOW_RECORDED', 'REFUND_REQUIRED', 'REFUNDED');

ALTER TABLE "Order" ADD COLUMN "publicTrackingToken" TEXT;
ALTER TABLE "OrderEvent" ADD COLUMN "kind" "OrderEventKind" NOT NULL DEFAULT 'STATUS_TRANSITION';

CREATE UNIQUE INDEX "Order_publicTrackingToken_key" ON "Order"("publicTrackingToken");
